In [2]:
import numpy as np

In [19]:
#嵌套的二维列表
data2_py=[[5.2,3.0,4.5],[9.1,0.1,0.3]]
#转为数组
data2_np=np.array(data2_py)
print(data2_np)
data2_np.shape                                     #查看数组形状

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


(2, 3)

In [22]:
n1=np.array(range(0,10),dtype=np.float64,ndmin=3)
print(n1)
n1.shape

[[[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]]]


(1, 1, 10)

In [20]:
#创建[1,100]内的等差数组，有5个元素，各元素为float16型
data3_np=np.linspace(1,100,num=5,dtype="float16")
print(data3_np)
data3_np.shape

[  1.    25.75  50.5   75.25 100.  ]


(5,)

In [17]:
#创建指数在[1,10]内、底数为3的等比数组，有10个元素，各元素为int型
data4_np=np.logspace(1,10,num=10,dtype=int,base=3)
print(data4_np)

[    3     9    27    81   243   729  2187  6561 19683 59049]


#### 生成随机数

In [ ]:
#用rand生成2行3列的数组，每个元素是(0,1)内的随机小数
rand1=np.random.rand(2, 3)
rand1
#print(type(rand1))

In [26]:
#用random生成2行5列的数组，每个元素是(0,1)内的随机小数
rand4=np.random.random(size=(2,5))
rand4
#print(type(rand4))

array([[0.16344333, 0.36988987, 0.92042423, 0.15805866, 0.61373117],
       [0.18947543, 0.40909584, 0.38115403, 0.88399902, 0.88639257]])

In [ ]:
#用randint生成1行5列的数组，每个元素是[1,100]内的随机整数
rand3=np.random.randint(1, 100,size=5)
print(rand3)

In [21]:
#用uniform生成4行2列的均匀分布的数组，每个元素是(0,1)内的随机小数
rand1=np.random.uniform(low=0.0, high=1.0, size=(4,2))
rand1

array([[0.74070162, 0.09270834],
       [0.54515396, 0.72837081],
       [0.16411505, 0.7980653 ],
       [0.9563887 , 0.54332539]])

### 练习1：使用PPT上面的每一个函数，各生成一个数组

In [ ]:
print(np.array(range(0,10),dtype=None,ndmin=1))
print(np.arange(0,20,2,dtype=None))
print(np.linspace(0,30,9,dtype=None))
print(np.logspace(1,10,num=10,base=2,dtype=int))
print(np.random.rand(10))
print(np.random.random(size=10))
print(np.random.randint(0,10,size=10,dtype=int))
print(np.random.uniform(0,10,size=10))s
print(np.random.normal(5,10,size=10))

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
[ 0.    3.75  7.5  11.25 15.   18.75 22.5  26.25 30.  ]
[   2    4    8   16   32   64  128  256  512 1024]
[0.77861203 0.09742858 0.02315248 0.11041331 0.40564032 0.47062667
 0.24480738 0.45492095 0.98235102 0.39495757]
[0.95269982 0.69470818 0.88818312 0.18512605 0.34040652 0.54927594
 0.99887908 0.60209553 0.11541891 0.23553614]
[7 4 2 1 1 9 6 2 7 8]
[2.34725141 1.60590956 0.84684765 5.2019075  5.42225532 1.06494193
 8.99300497 7.1041522  7.22469548 0.84852417]
[15.38937783  4.61662166  5.30084629  8.45764354  2.49279698 27.62358745
  4.51176881 -2.66672536 11.57646031  1.86112397]


In [31]:
#创建特殊数组
z1=np.zeros((3,4))                #3行4列的0数组
e1=np.empty(3)                    #空数组
print("z1是：",z1)
print("\ne1是：",e1)

z1是： [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

e1是： [0. 0. 0.]


### 练习2：使用PPT上的zeros、ones、eye、identity等函数，各生成一个特殊数组

In [40]:
print(np.zeros((2,3)))
print(np.eye(2,3))
# print(np.empty((3,3)))
print(np.identity(2))
print(np.ones((2,3)))
print(np.full((2,3), 6))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]]
[[1. 0.]
 [0. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[6 6 6]
 [6 6 6]]


In [ ]:
#导入random模块
from numpy import random

In [20]:
print(random.rand(10))                     #导入random模块，再使用其中的函数，则不用写np
print(random.randint(0,50,5))

s=random.normal(0,1,1000)                #正态分布数组
print(s)
print(random.standard_normal(8))         #标准正态分布数组


[0.30579963 0.93965437 0.28795076 0.47371309 0.35428845 0.67955427
 0.80004615 0.80060018 0.62978614 0.35927705]
[25 45 18 48 34]
[ 0.19873622  0.07182165 -0.34907678  0.94686499 -1.22584169 -1.49276417
  2.39012915 -0.990622  ]
