# 二、DataFrame对象
## 2.1  创建DataFrame对象

In [1]:
import pandas as pd

In [18]:
#例2-1 将 嵌套的列表（二维） 转为  数据框
data=[[3,0],[2,3],[0,7],[1,2]]
index=['a','b','c', 'd']
pd.DataFrame( data, index, columns=['apples','oranges'])

apples  oranges
a       3        0
b       2        3
c       0        7
d       1        2

In [3]:
#例2-1 创建各城市的人口、GDP增速数据框。
#方法一：
data=[ [710.1,8.4],[536,8.7],[261.1,8.1],[1500.1,8.6] ]
index=['福州','南昌','厦门', '成都']
pd.DataFrame( data, index, columns=['人口','GDP增速']) 

人口  GDP增速
福州   710.1    8.4
南昌   536.0    8.7
厦门   261.1    8.1
成都  1500.1    8.6

In [13]:
#例2-2 创建各城市的人口、GDP增速数据框。
#方法二：
#步骤1：先创建3列的Series
s1=pd.Series({"福州":710.1,"南昌":536,"厦门":261.1,"成都":1500.1})    #人口
s2=pd.Series({"福州":8.4,"南昌":8.7,"厦门":8.1,"成都":8.6})           #2021年GDP增速，百分比
s3=pd.Series({"福州":26,"南昌":23,"厦门":27,"成都":22})               #白天平均气温
print("系列s1是：\n",s1)
#步骤2：将3个Series列合并，字典键值设置列标签
df7=pd.DataFrame({"人口":s1,"GDP增速":s2,"白天平均气温":s3})
print("\n数据框是：\n",df7)

系列s1是：
 福州     710.1
南昌     536.0
厦门     261.1
成都    1500.1
dtype: float64

数据框是：
         人口  GDP增速  白天平均气温
福州   710.1    8.4      26
南昌   536.0    8.7      23
厦门   261.1    8.1      27
成都  1500.1    8.6      22


In [14]:
#方法三：index设置行标签
df8=pd.DataFrame( [s2,s1,s3] ,index=["GDP增速","人口","白天平均气温"])   #注意，第一个列表中的元素即第一行，与行标签位置、个数一一对应
#解析：嵌套列表的格式中，内部的一个列表视为二维的一行，例如，[ [710.1,8.4],[536,8.7],[261.1,8.1],[1500.1,8.6] ]中的[710.1,8.4]是二维的第一行。
#同理，[s2,s1,s3]中的系列s2会被视为二维数据框的一行
df8

福州     南昌     厦门      成都
GDP增速     8.4    8.7    8.1     8.6
人口      710.1  536.0  261.1  1500.1
白天平均气温   26.0   23.0   27.0    22.0

In [17]:
#例2-3 将各路车站点Series 合并 为line数据框

#pd.set_option("display.unicode.ambiguous_as_wide",True)           #使列名对齐
#pd.set_option("display.unicode.east_asian_width",True)  

#多个系列“横向”合并为数据框，注意，字典的值必须为系列型，才能正确合并，不可以是列表。

line=pd.DataFrame({'1路': pd.Series(['火车站', '金榜公园', '文灶', '将军祠', '文化宫', '中山公园', '镇海路', '博物馆', '厦大']),\
      '759路': pd.Series(['厦大西村', '软件园', '高林', '厦大翔安校区']), \
      '30路': pd.Series(['会展中心', '瑞景商业广场', '火车站']), \
      '3路': pd.Series(['文化宫', '火车站', '文灶', '中山公园', '轮渡']), \
      '100路': pd.Series(['轮渡', '东渡', '海沧', ''])})
line

1路    759路     30路    3路 100路
0   火车站    厦大西村    会展中心   文化宫   轮渡
1  金榜公园     软件园  瑞景商业广场   火车站   东渡
2    文灶      高林     火车站    文灶   海沧
3   将军祠  厦大翔安校区     NaN  中山公园     
4   文化宫     NaN     NaN    轮渡  NaN
5  中山公园     NaN     NaN   NaN  NaN
6   镇海路     NaN     NaN   NaN  NaN
7   博物馆     NaN     NaN   NaN  NaN
8    厦大     NaN     NaN   NaN  NaN

#### 其它创建方法

In [2]:
#例 其他创建方式
#由多维数组创建
import numpy as np

d1=np.arange(10,22).reshape(3,4)
df1=pd.DataFrame(d1)
print("由多维数组创建\n",df1,"\n")

df2=pd.DataFrame(d1,columns=['y1','y2','y3','y4'])        #添加列标签
print("由多维数组创建，加列标签\n",df2,"\n")


#多个字典沿0軕（“纵向”）合并
d3= [{'a': 1, 'b': 2},{'a': 5, 'b': 10, 'c': 20}]
df3 = pd.DataFrame(d3)                                  #没有对应的部分数据为 NaN
print("由多个字典合并\n",df3,"\n")

#key为列索引，series数据创建
d4 = {
    "one": pd.Series([1.0, 2.0, 3.0], index=["a", "b", "c"]),                #字典key是列索引
    "two": pd.Series([1.0, 2.0, 3.0, 4.0], index=["a", "b", "c", "d"]),
}
df4 = pd.DataFrame(d4)                                                         #没有对应的部分数据为 NaN
print("由字典创建\n",df4,"\n")

由多维数组创建
     0   1   2   3
0  10  11  12  13
1  14  15  16  17
2  18  19  20  21 

由多维数组创建，加列标签
    y1  y2  y3  y4
0  10  11  12  13
1  14  15  16  17
2  18  19  20  21 

由多个字典合并
    a   b     c
0  1   2   NaN
1  5  10  20.0 

由字典创建
    one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0 



In [10]:
#由嵌套的列表创建，与numpy的区别之一：允许各列的数据类型不一样
d5 = [['Google',10],['Runoob',12],['Wiki',13]]
df5 = pd.DataFrame(d5,columns=['Site','Age'])
print("由嵌套的列表创建\n",df5,"\n")

由嵌套的列表创建
      Site  Age
0  Google   10
1  Runoob   12
2    Wiki   13 



#### 练习4 创建df_1数据框如下，值为随机数：
```
       k1      k2
s1  0.343305  0.439486
s2  0.854493  0.686528
s3  0.028732  0.241264

```

In [8]:
d_1 = {
    "k1": pd.Series([np.random.random(),np.random.random(),np.random.random()],index=["s1","s2","s3"]),
    "k2": pd.Series([np.random.random(),np.random.random(),np.random.random()],index=["s1","s2","s3"]),
}
df_1=pd.DataFrame(d_1)
print(df_1)

          k1        k2
s1  0.335318  0.640232
s2  0.961787  0.910760
s3  0.893336  0.450803


### 2.2.1  查看DataFrame的常用属性

In [ ]:
#例3-1 显示line的标签、数据类型、非空等信息
line.info()

In [ ]:
##例3-2 显示line的值及类型，注意，是numpy二维数组
print("line的值是：\n",line.values)
print("数据框值的类型是\n",type(line.values))
print("数据框值的类型是\n",type(line.values.dtype))
#解析：可以使用  DateFrame.to_numpy() 或 DateFrame.values 将DateFrame转换为 NumPy 数组
#DateFrame可以含不同数据类型，numpy只能同一种数据类型，为什么都能转为numpy呢？（可以问问KIMI或豆包等AI）

In [30]:
##例3-3 将line转置
line.T

0       1    2       3    4     5    6    7    8
1路     火车站    金榜公园   文灶     将军祠  文化宫  中山公园  镇海路  博物馆   厦大
759路  厦大西村     软件园   高林  厦大翔安校区  NaN   NaN  NaN  NaN  NaN
30路   会展中心  瑞景商业广场  火车站     NaN  NaN   NaN  NaN  NaN  NaN
3路     文化宫     火车站   文灶    中山公园   轮渡   NaN  NaN  NaN  NaN
100路    轮渡      东渡   海沧          NaN   NaN  NaN  NaN  NaN

#### 练习5：
1. 生成df_2数据框，数据是[1,100]间的随机数，30行3列，列标签为k1,k2,k3
```
      k1  k2   k3
0  92  51   38
1  19  62   91
2  15  62    3
3  42  10   17
4  55  42   82
  ..........
  ...........
```
2. 查看df_2的信息

In [14]:
d_2={
    "k1": pd.Series(np.random.randint(1,100,size=30)),
    "k2": pd.Series(np.random.randint(1,100,size=30)),
    "k3": pd.Series(np.random.randint(1,100,size=30))
}
df_2=pd.DataFrame(d_2)
print(df_2)

    k1  k2  k3
0    5  96   7
1   20  54  62
2    6  93  88
3   92  62  65
4   59  99  31
5   90  95  89
6    6  30  28
7   92  54   9
8   96  86  13
9   47  75  87
10  29  49  82
11   1  48  36
12  34  75   4
13  43  74  54
14  12  45  99
15  53  63  12
16  67  65  83
17  89  46  34
18  73  96  76
19  40  55   3
20  25  14  66
21  68  69   1
22  41   1  13
23   5  71  60
24  79  33  19
25  99  59  57
26  34  92  92
27  14  34  97
28  29  11  84
29  74  14  77


In [15]:
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   k1      30 non-null     int32
 1   k2      30 non-null     int32
 2   k3      30 non-null     int32
dtypes: int32(3)
memory usage: 492.0 bytes


In [16]:
print("df_2的值是：\n",df_2.values)

df_2的值是：
 [[ 5 96  7]
 [20 54 62]
 [ 6 93 88]
 [92 62 65]
 [59 99 31]
 [90 95 89]
 [ 6 30 28]
 [92 54  9]
 [96 86 13]
 [47 75 87]
 [29 49 82]
 [ 1 48 36]
 [34 75  4]
 [43 74 54]
 [12 45 99]
 [53 63 12]
 [67 65 83]
 [89 46 34]
 [73 96 76]
 [40 55  3]
 [25 14 66]
 [68 69  1]
 [41  1 13]
 [ 5 71 60]
 [79 33 19]
 [99 59 57]
 [34 92 92]
 [14 34 97]
 [29 11 84]
 [74 14 77]]


In [17]:
print("数据框值的类型是\n",type(df_2.values))
print("数据框值的类型是\n",type(df_2.values.dtype))

数据框值的类型是
 <class 'numpy.ndarray'>
数据框值的类型是
 <class 'numpy.dtypes.Int32DType'>


In [18]:
print("转置：",df_2.T)

转置：     0   1   2   3   4   5   6   7   8   9   ...  20  21  22  23  24  25  26  \
k1   5  20   6  92  59  90   6  92  96  47  ...  25  68  41   5  79  99  34   
k2  96  54  93  62  99  95  30  54  86  75  ...  14  69   1  71  33  59  92   
k3   7  62  88  65  31  89  28   9  13  87  ...  66   1  13  60  19  57  92   

    27  28  29  
k1  14  29  74  
k2  34  11  14  
k3  97  84  77  

[3 rows x 30 columns]
