In [2]:
import numpy as np

In [2]:
#数组的转置
a = np.arange(12)
print ('原数组：')
print (a)
print ('一维转置数组：')
print (a.T)                           #一维数组转置后与原来的一样

b = np.arange(12).reshape(3,4) 
print ('\n原数组：')
print (b)

print ('\n多维转置数组：')
print (b.T)

原数组：
[ 0  1  2  3  4  5  6  7  8  9 10 11]
一维转置数组：
[ 0  1  2  3  4  5  6  7  8  9 10 11]

原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

多维转置数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [3]:
#修改数组形状为5行2列
a = np.arange(10)
print ('原始数组：')
print (a)
 
b = a.reshape(5,2)
print ('\n修改后的数组：')
print (b)

原始数组：
[0 1 2 3 4 5 6 7 8 9]

修改后的数组：
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [4]:
#默认按行，将b展开为一维数组
c=b.flatten()                           #产生b的副本，c与b无关
d=b.ravel()                             #产生b的视图，d与b相关，同步变化
print ('原始数组：')
print (b)
print ('\n flatten展开的数组：')
print (c)

print ('\n ravel展开的数组：')
print (d)
print()

#按列展开一维数组
print ('\n 以 F (列)风格顺序展开的数组：')
print (b.flatten(order = 'F'))

原始数组：
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

 flatten展开的数组：
[0 1 2 3 4 5 6 7 8 9]

 ravel展开的数组：
[0 1 2 3 4 5 6 7 8 9]


 以 F (列)风格顺序展开的数组：
[0 2 4 6 8 1 3 5 7 9]


In [5]:
#修改c与d，观察a与b的变化。
c[0]=100
d[1]=200
print("b数组:\n",b)
print("a数组:\n",a)

#修改原数据，视图随之而变，副本不变。
a[2]=300
print("b数组:\n",b)
print("c数组:\n",c)

b数组:
 [[  0 200]
 [  2   3]
 [  4   5]
 [  6   7]
 [  8   9]]
a数组:
 [  0 200   2   3   4   5   6   7   8   9]
b数组:
 [[  0 200]
 [300   3]
 [  4   5]
 [  6   7]
 [  8   9]]
c数组:
 [100   1   2   3   4   5   6   7   8   9]


###  回答：
```
reshape flatten ravel中哪个函数实现了深拷贝，产生副本？哪些产生视图？（注：修改视图影响原数据。）
```

flatten实现了深拷贝，产生副本。ravel产生视图。

In [6]:
a = np.array([[1,2],[3,4]])
 
print ('第一个数组：')
print (a)

b = np.array([[5,6],[7,8]])
print ('\n 第二个数组：')
print (b)

c = np.array([[9,10],[11,12]])
print ('\n 第三个数组：')
print (b)

print ('\n 水平堆叠3个数组：')
abc_h=np.hstack((a,b,c))
print (abc_h)

abc_v=np.vstack((a,b,c)) 
print ('\n 垂直堆叠3个数组：')
print (abc_v)

第一个数组：
[[1 2]
 [3 4]]

 第二个数组：
[[5 6]
 [7 8]]

 第三个数组：
[[5 6]
 [7 8]]

 水平堆叠3个数组：
[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]

 垂直堆叠3个数组：
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [7]:
print ('沿轴 0 连接两个数组：')
print (np.concatenate((a,b)))
 
print ('\n 沿轴 1 连接两个数组：')
print (np.concatenate((a,b),axis = 1))

沿轴 0 连接两个数组：
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

 沿轴 1 连接两个数组：
[[1 2 5 6]
 [3 4 7 8]]


### 练习1：用随机函数创建3个2行3列的整数数组，练习上面的函数，转置、横向、纵向组合各举一例

In [8]:
a=np.random.randint(1,100,size=(2,3))
b=np.random.randint(1,100,size=(2,3))
c=np.random.randint(1,100,size=(2,3))
print(a)
print(b)
print(c)
print(a.T)
abc_h=np.hstack((a,b,c))
abc_v=np.vstack((a,b,c))
print(abc_h)
print(abc_v)
print(np.concatenate((a,b),axis=0))
print(np.concatenate((b,c),axis=1))

[[32 48 30]
 [56 41 56]]
[[76 24 59]
 [72 41 25]]
[[65 77 56]
 [32 48 25]]
[[32 56]
 [48 41]
 [30 56]]
[[32 48 30 76 24 59 65 77 56]
 [56 41 56 72 41 25 32 48 25]]
[[32 48 30]
 [56 41 56]
 [76 24 59]
 [72 41 25]
 [65 77 56]
 [32 48 25]]
[[32 48 30]
 [56 41 56]
 [76 24 59]
 [72 41 25]]
[[76 24 59 65 77 56]
 [72 41 25 32 48 25]]


In [8]:
print(abc_h)
print ('\n 将数组分为三个大小相等的子数组：')
b = np.split(abc_h,3,axis=1)
print (b)

 
print ('\n 将数组在一维数组中表明的位置分割：')
b = np.split(abc_h,[1,3],axis=1)
print (b)

[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]

 将数组分为三个大小相等的子数组：
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]

 将数组在一维数组中表明的位置分割：
[array([[1],
       [3]]), array([[2, 5],
       [4, 7]]), array([[ 6,  9, 10],
       [ 8, 11, 12]])]


In [9]:
print ('原array：')
print(abc_h)
 
print ('\n 横向（沿1轴）平均拆分后：')
print(np.hsplit(abc_h, 3))

原array：
[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]

 横向（沿1轴）平均拆分后：
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [10]:
print ('原array：')
print(abc_v)
 
print ('\n 纵向（沿0轴）平均拆分后：')
print(np.vsplit(abc_v, 3))

原array：
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

 纵向（沿0轴）平均拆分后：
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


### 练习2：用随机函数创建1个6行8列的整数数组，练习上面的函数，横向、纵向分割各举一例

In [11]:
arr=np.random.randint(1,100,size=(6,8))
print(arr)
print(np.hsplit(arr,4))
print(np.vsplit(arr,3))

[[33 59 77 31  4 42 70 83]
 [68 61 65 36 94 92 94 34]
 [63 71 13  5 90 14 63 87]
 [81 84 41 77 28 55  6 28]
 [15 96 69 24 72 14  2  9]
 [73 79 46 88 10 16 56 79]]
[array([[33, 59],
       [68, 61],
       [63, 71],
       [81, 84],
       [15, 96],
       [73, 79]], dtype=int32), array([[77, 31],
       [65, 36],
       [13,  5],
       [41, 77],
       [69, 24],
       [46, 88]], dtype=int32), array([[ 4, 42],
       [94, 92],
       [90, 14],
       [28, 55],
       [72, 14],
       [10, 16]], dtype=int32), array([[70, 83],
       [94, 34],
       [63, 87],
       [ 6, 28],
       [ 2,  9],
       [56, 79]], dtype=int32)]
[array([[33, 59, 77, 31,  4, 42, 70, 83],
       [68, 61, 65, 36, 94, 92, 94, 34]], dtype=int32), array([[63, 71, 13,  5, 90, 14, 63, 87],
       [81, 84, 41, 77, 28, 55,  6, 28]], dtype=int32), array([[15, 96, 69, 24, 72, 14,  2,  9],
       [73, 79, 46, 88, 10, 16, 56, 79]], dtype=int32)]
