In [1]:
import numpy as np 

In [2]:
a = np.arange(9, dtype = np.float_).reshape(3,3)  
print ('第一个数组：')
print (a)

print ('\n数组与标量相加：')
print (a+100)

print ('\n第二个数组：')
b = np.array([10,10,10])  
print (b)

print ('\n两个数组相加：')
print (a+b)

print ('\n两个数组相减：')
print (b-a)

print ('\n两个数组相乘：')
print (a*b)

print ('\n两个数组相除：')
print (a/b)

print ('\n两个数组整除：')              
print (a//b)

第一个数组：
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]

数组与标量相加：
[[100. 101. 102.]
 [103. 104. 105.]
 [106. 107. 108.]]

第二个数组：
[10 10 10]

两个数组相加：
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]

两个数组相减：
[[10.  9.  8.]
 [ 7.  6.  5.]
 [ 4.  3.  2.]]

两个数组相乘：
[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]

两个数组相除：
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]

两个数组整除：
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
#数组与标量比较
a=np.arange(1,10)
print ('a数组：',a)
print("a>5:\t\t",a>5)
print("a!=7:\t\t",a!=7)

print("a!=7:\t\t",~(a==7))                               # ~逻辑非运算
print("a>5 并且 a!=7：\t",(a>5) & (a!=7) )               # &逻辑且运算
print("a>5 并且 a!=7：\t",np.logical_and(a>5,a!=7))      #用函数实现并且关系

a数组： [1 2 3 4 5 6 7 8 9]
a>5:		 [False False False False False  True  True  True  True]
a!=7:		 [ True  True  True  True  True  True False  True  True]
a!=7:		 [ True  True  True  True  True  True False  True  True]
a>5 并且 a!=7：	 [False False False False False  True False  True  True]
a>5 并且 a!=7：	 [False False False False False  True False  True  True]


#### **布尔索引**：比较运算为索引，实现条件选择
- 数组支持用包含True、False的数组为下标来访问其中的元素，返回True对应位置上元素组成的数组。
- 提示：更多数组的索引知识，见**访问数组**

In [4]:
print(a[a>5])
print(a[np.logical_and(a>5,a!=7)])

[6 7 8 9]
[6 8 9]


In [5]:
#数组与数组比较
a=np.random.randint(1,50,6).reshape(2,3)
print ('a数组：',a)
b=np.random.randint(1,50,6).reshape(2,3)
print ('b数组：',b)
print("a>b:  ",a>b)


#比较运算为索引，实现条件选择
#数组支持用包含True、False的数组为下标来访问其中的元素，返回True对应位置上元素组成的数组。
print("输出a>b的元素:  ",a[a>b])

a数组： [[16 29 40]
 [39 39 40]]
b数组： [[36 18 38]
 [25 23 23]]
a>b:   [[False  True  True]
 [ True  True  True]]
输出a>b的元素:   [29 40 39 39 40]


In [6]:
# 点积运算
a = np.array([1,2,3,4])
b = np.array([1,10,100,1000])
print("\n 一维a与b的点积是：",np.dot(a,b))
 
a = np.array([[1,2],[3,4]])
b = np.array([[10,100],[10,100]])
print("\n 二维a与b的点积是：",np.dot(a,b))

print("\n a与b的矩阵乘积是：",np.matmul(a,b))               #matmul是数组的矩阵乘函数



 一维a与b的点积是： 4321

 二维a与b的点积是： [[ 30 300]
 [ 70 700]]

 a与b的矩阵乘积是： [[ 30 300]
 [ 70 700]]


### 练习：+-*/与点积运算各举一例

In [10]:
a=np.random.randint(1,100,size=(2,3))
b=np.random.randint(1,100,size=(2,3))
print(a)
print(b)
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a//b)
b.resize((3,2))
print(b)
print(np.dot(a,b))
print(np.matmul(a,b))

[[87 58  4]
 [79  9 97]]
[[44 22 99]
 [56 61  9]]
[[131  80 103]
 [135  70 106]]
[[ 43  36 -95]
 [ 23 -52  88]]
[[3828 1276  396]
 [4424  549  873]]
[[ 1.97727273  2.63636364  0.04040404]
 [ 1.41071429  0.14754098 10.77777778]]
[[ 1  2  0]
 [ 1  0 10]]
[[44 22]
 [99 56]
 [61  9]]
[[ 9814  5198]
 [10284  3115]]
[[ 9814  5198]
 [10284  3115]]
