### 一、一维数组的索引与切片
    与python的列表索引与切片相同

### 二、二维数组的索引与切片
    数组名[行下标]            :行下标可以是索引、切片，指定要访问的行
    数组名[行下标,列下标]      :行、列下标可以是索引、切片，通过行、列两个维度确定访问位置
    数组名[(行下标,列下标)]    ：同上
* 注意索引与切片的区别，若是索引，则结果是一维数组。

In [1]:
import numpy as np

In [5]:
data2=np.arange(25).reshape(5,5)
print(data2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [4]:
print("data2[2,2]访问的元素是：")
print(data2[2,2])

data2[2,2]访问的元素是：
12


In [6]:
print("data2[1:3,2]访问的元素是：")
print(data2[1:3,2])                          #采用索引，则是行、列索引确定的元素  组成的   一维数组

data2[1:3,2]访问的元素是：
[ 7 12]


In [7]:
print("data2[1:3,2:3]访问的元素是：")
print(data2[1:3,2:3])                         #注意与上一例的区别，采用切片，原矩阵中切出小矩阵

data2[1:3,2:3]访问的元素是：
[[ 7]
 [12]]


In [9]:
print("data2[-3:-1,1:2]访问的元素是：")
print( data2[-3:-1,1:2])

data2[-3:-1,1:2]访问的元素是：
[[11]
 [16]]


In [10]:
print(" data2[:7:2,2:8:3]访问的元素是：")
print(  data2[:7:2,2:8:3])

 data2[:7:2,2:8:3]访问的元素是：
[[ 2]
 [12]
 [22]]


### 练习1：
    data=np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],  [20,21,22,23,24]])
    访问其中第5行第2-3列的元素
    输出样例:
    [21 22]

In [ ]:
data=np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]])
# print(data)
# print(data[4,1],data[4,2])
# print(data[4:5,1:3])
# print(data[-1:,1:3])
print(data[-1,1:3])

[21 22]


### 三、花式索引
    数组名[行下标]
    数组名[行下标,列下标]
* 注意：花式索引的行、列下标是整数数组，整数数组可以是NumPy数组，也可以是Python中列表、元组等可迭代类型
* 花式索引、布尔数组是将数据复制到新数组中，因此改变新数组的值不会影响原数组。


In [11]:
data2=np.array([[0,1,2,3,4],[5,6,7,8,9],
                [10,11,12,13,14],[15,16,17,18,19],  [20,21,22,23,24]])
print( data2[[0,1,2,3],[1,2,3,4]] )              #等价于：data[0,1]、data[1,2]、data[2,3]、data[3,4]

#判断a的数据是否来源于其它对象
a=data2[[0,1,2,3],[1,2,3,4]]
print("\n a的数据是否来源于其它对象：\n",a.base)

[ 1  7 13 19]

 a的数据是否来源于其它对象：
 None


In [14]:
data1 = np.array([[1,2,3], [4,5,6],[7,8,9]]) 
b = data1[1:3,[1,2]] 
print(b)
print("\n b的数据是否来源于data1：\n",b.base)          #有切片索引，b与data1共享数据

[[5 6]
 [8 9]]

 b的数据是否来源于data1：
 [[5 8]
 [6 9]]


### 练习2：
    data=np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],  [20,21,22,23,24]])
    访问其中前3行第2、4、5列的元素
    输出样例:
    [[ 1  3  4]
      [ 6  8  9]
     [11 13 14]]

In [13]:
data=np.array([[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],  [20,21,22,23,24]])
# print(data)
print(data[0:3,[1,3,4]])

[[ 1  3  4]
 [ 6  8  9]
 [11 13 14]]


### 四、布尔索引
    索引是布尔数组，例如，np.array([1,0,1,1],dtype=bool)

In [22]:
data=np.arange(12).reshape(4,3)
bl=np.array([1,0,1,1],dtype=bool)              #1表示True，0表示False

print("data：\n",data)
print("布尔数组是：\n",bl)

data=data[bl,0:2]                              #行下标是布尔值，取下标为1（True）对应的行
print("查找结果是：\n",data)

data：
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
布尔数组是：
 [ True False  True  True]
查找结果是：
 [[ 0  1]
 [ 6  7]
 [ 9 10]]


In [25]:
#例题：查找data数组中>5的元素
data=np.arange(12).reshape(4,3)
print ('数组比较运算，判断大于5的元素：') 
print (    data > 5   )                      #得到布尔数组


print ('输出大于5的元素：') 
print (   data[ data > 5 ]   )                #用布尔索引来获取符合指定条件的元素

数组比较运算，判断大于5的元素：
[[False False False]
 [False False False]
 [ True  True  True]
 [ True  True  True]]
输出大于5的元素：
[ 6  7  8  9 10 11]


### 练习3：
    data=np.random.randint(0,100,24).reshape(8,3)
    输出其中>85或<60的元素
    输出样例:
    [95 29 27 25 87 50 16 93 89 54 40 91 15 19 53 44 27 95 90]

In [21]:
data=np.random.randint(0,100,24).reshape(8,3)
# print(data)
print(data[(data>85) | (data<60)])

[ 3  9 86 89 15 95 13 53 10 26 91 27 59 38 26 55 86]
