In [1]:
import numpy as np

### 一、统计函数
    np.amin(a,axis)      :计算数组中的元素沿指定轴的最小值
    np.amax(a,axis)      :计算数组中的元素沿指定轴的最大值
    np.sum(a, axis)      :计算数组中的元素沿指定轴的和
    np.median(a, axis)   :计算数组中的元素沿指定轴的中位数（中值）
    np.std(a, axis)      :计算数组中的元素沿指定轴的标准差
    np.var(a, axis)      :计算数组中的元素沿指定轴的方差

* 默认情况下，函数并不按照任一轴向计算，而是计算一个总值。
* 
当axis参数为0时，表示沿着纵轴进行计算；当axis为1时，表示沿着横轴进行计算。


In [4]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]])  
print ('我们的数组是：')
print (a)

print ('\n调用 amin() 函数沿1轴求最小：')
print (np.amin(a,1))

print ('\n调用 amax() 函数求所有元素最大值：')
print (np.amax(a))

print ('\n调用 sum() 函数沿0轴求和：')
print (np.sum(a, axis =  0))

print ('\n再次调用 sum() 函数求所有元素之和：')
print (np.sum(a))

print ('\n调用 std() 函数沿0轴求标准差：')
print (np.std(a, axis =  0))

print ('\n调用 std() 函数沿0轴求方差：')
print (np.var(a, axis =  0))

我们的数组是：
[[3 7 5]
 [8 4 3]
 [2 4 9]]

调用 amin() 函数沿1轴求最小：
[3 3 2]

调用 amax() 函数求所有元素最大值：
9

调用 sum() 函数沿0轴求和：
[13 15 17]

再次调用 sum() 函数求所有元素之和：
45

调用 std() 函数沿0轴求标准差：
[2.62466929 1.41421356 2.49443826]

调用 std() 函数沿0轴求方差：
[6.88888889 2.         6.22222222]


### 练习1：
1. 生成一个二维的随机数组
2. 求数组所有元素的最大值
3. 按数组各列的和

In [4]:
arr=np.random.randint(0,100,(3,4))
print(arr)
print(np.amax(arr))
print(np.sum(arr,axis=0))

[[77 41 45 30]
 [91 60 70 37]
 [ 5 75 40 42]]
91
[173 176 155 109]


### 二、排序
    np.sort(a, axis, kind)       ：返回输入数组的排序副本
    np.argsort(a, axis, kind)    ：返回的是数组元素从小到大排序后所对应的索引值
* axis默认值为-1，表示沿最后的轴排序，axis=None表示展开来排序。如果是二维数组，axis可选0、1，axis=0表示按列排序，axis=1表示按行排序。
* kind设置排序的算法，包含quicksort（快速排序）、mergesort（归并排序）、heapsort（堆排序），默认为quicksort。



In [10]:
a = np.array([[3,11,2],[30,1,200]])  
print ('我们的数组是：')
print (a)

print ('调用 sort() 函数，默认按1轴方向（行）升序排：')
print (np.sort(a))                                       #注意：每行单独排序，原同列的数据可能变不同列

print ('按列排序：')
print (np.sort(a, axis =  0))

我们的数组是：
[[  3  11   2]
 [ 30   1 200]]
调用 sort() 函数，默认按1轴方向（行）升序排：
[[  2   3  11]
 [  1  30 200]]
按列排序：
[[  3   1   2]
 [ 30  11 200]]


In [12]:
a=np.array([11,8,13,9,12,10])
b=np.argsort(a)
print("argsort后索引",b)

#以排序后的索引重构原数组
print("利用argsort显示a的排序结果",a[b])


argsort后索引 [1 3 5 0 4 2]
利用argsort显示a的排序结果 [ 8  9 10 11 12 13]


In [40]:
#例题：请将a按第2列的降序排序
a=np.array([[3,11,2],[30,1,200]]) 
print("原数组：")
print(a)
b=np.argsort(a,axis=0)
print("argsort后索引\n",b)

sort_by=b[:,1]                                         #取出第2列的升序索引值
sort_by=sort_by[::-1]                                   #取反，求降序的索引值
print("利用argsort显示a的排序结果\n",a[sort_by])         #按排序索引值的顺序显示 a

原数组：
[[  3  11   2]
 [ 30   1 200]]
argsort后索引
 [[0 1 0]
 [1 0 1]]
利用argsort显示a的排序结果
 [[  3  11   2]
 [ 30   1 200]]


### 练习2：
1. 生成5行3列的二维随机数组
2. 将数组按第3列的降序排列

In [7]:
arr=np.random.randint(0,100,size=(5,3))
print(arr)
b=np.argsort(arr,axis=0)
# print(b)
sorted_b=b[:,2]
sorted_b=sorted_b[::-1]
print(arr[sorted_b])

[[56 27  7]
 [66 48 74]
 [12  2 30]
 [55 50 70]
 [27 77 82]]
[[27 77 82]
 [66 48 74]
 [55 50 70]
 [12  2 30]
 [56 27  7]]


### 三、查询
    np.where(条件)          ：返回输入数组中满足给定条件的元素的索引
    np.extract(条件,数组)   ：返回满足条件的数组元素

In [36]:
x = np.arange(9.).reshape(3,  3)  
print ('我们的数组是：')
print (x)

print ( '\n大于 3 的元素的索引：')
y = np.where(x >  3)  
print (y)                   #(y[0],y[1])分别为行索引、列索引

print ('\n使用这些索引来获取满足条件的元素：')
print (x[y])               #布尔索引

print ('\nextract获取满足条件的元素：')
z = np.extract(x > 3,x)  
print (z)

我们的数组是：
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]

大于 3 的元素的索引：
(array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))

使用这些索引来获取满足条件的元素：
[4. 5. 6. 7. 8.]

extract获取满足条件的元素：
[4. 5. 6. 7. 8.]


### 练习3：
1. 生成5行3列的二维随机数组，元素值在0-200之间
2. 查询数组中值大于20的元素及其在数组中的位置

In [11]:
arr=np.random.randint(0,200,size=(5,3))
print(arr)
print(np.where(arr>20))
print(np.extract(arr>20,arr))

[[ 24 195  67]
 [ 59  29  34]
 [ 67 126  37]
 [ 85 161  10]
 [ 86 120   4]]
(array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 4, 4]), array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 0, 1]))
[ 24 195  67  59  29  34  67 126  37  85 161  86 120]
