### 读写文件
#### 一、文件中的数据读入数组：
* numpy.loadtxt( fname ,  delimiter ,  encoding ,  dtype)

        fname：文件路径与文件名
        delimiter：分隔数值的分隔符
        encoding：文本的编码方式，默认UTF-8
        dtype：数据的类型，默认float，按科学记数法显示。
        
#### 二、设置数组打印格式：        
* np.set_printoptions(precision,suppress)   ：设置数据的显示格式

        precision设置小数的位数。
        suppress设置为True，数据以定点法显示；设置为False，则以科学记数法显示。
        其它参数可自行百度。
        
#### 三、数组写入文件：
* numpy.savetxt(fname, X, fmt='%.18e', delimiter=' ', encoding)
        
        fname：文件路径与文件名
        X：需要存入文件的数组数据
        fmt：数据的格式，默认采用18位小数的科学记数法
        delimiter：用于分隔数值的分隔符
        encoding：数据存储的编码方式，默认UTF-8

In [1]:
import numpy as np

In [2]:
#例1-1，读入a0.txt中的数据，每列数据之间以制表符分隔
array1=np.loadtxt(".//a0.txt", delimiter='\t')              #a0.txt若不在当前文件夹下，请添加a0.txt的路径
print("a0的内容是：\n",array1)

a0的内容是：
 [[13.07 11.97]
 [ 4.8   4.33]
 [22.75 22.25]
 ...
 [ 6.17  6.04]
 [ 4.71  4.52]
 [ 4.98  4.91]]


In [3]:
#例1-2，读入a1.txt中的数据，每列数据之间以制表符分隔。
#注意：a1.txt文件采用utf-16编码
#array1=np.loadtxt(".//a1.txt", delimiter='\t')     #文件打开错误，因为文件的编码格式不是utf-8
array2=np.loadtxt(".//a1.txt", delimiter='\t',encoding='utf-16')     #a1.txt若不在当前文件夹下，请添加a1.txt的路径
print("\na1的内容是：\n",array1)


a1的内容是：
 [[13.07 11.97]
 [ 4.8   4.33]
 [22.75 22.25]
 ...
 [ 6.17  6.04]
 [ 4.71  4.52]
 [ 4.98  4.91]]


In [ ]:
#例2，设置print以定点法输出数据，3位小数
np.set_printoptions(precision=3,suppress=True)       #precision设置显示3位小数,suppress设置以定点法显示数据
print(np.array([3e-1,1e-9,5.1234567e-2]))

[0.3   0.    0.051]


### 练习1：读入a1.txt中的数据，保存至数组array3中

In [8]:
array3=np.loadtxt(".//a1.txt",delimiter='\t',encoding='utf-16',dtype=float)
print(array3)

[[13.07 11.97]
 [ 4.8   4.33]
 [22.75 22.25]
 ...
 [ 6.17  6.04]
 [ 4.71  4.52]
 [ 4.98  4.91]]


In [20]:
#例3，将数组[1.11 , 2.22 , 3.33]存入a.txt文件，采用1位小数的格式
import numpy as np
np.savetxt( ".//a.txt",    np.array( [1.11 , 2.22 , 3.33]))

###  练习2：
1. 将练习1所得的array3中的数据乘2
2. 结果存入c.txt文件，用逗号分隔，数据保存2位小数

In [14]:
array4=array3*2
print(array4)
np.savetxt(".//c.txt",array4,fmt='%g',delimiter='\t',encoding='utf-16')

[[26.14 23.94]
 [ 9.6   8.66]
 [45.5  44.5 ]
 ...
 [12.34 12.08]
 [ 9.42  9.04]
 [ 9.96  9.82]]
