### 练习
1. 读入stock0.txt中的数据，每列数据之间以制表符分隔。其中，一行一只股票，第一列是前一天的收盘价，第二列是当天的收盘价
2. 计算每只股票的涨跌值与涨跌幅，涨跌幅=涨跌值/前一天的收盘价
3. 合并数据，组成(6000,4)数组，每列分别是 前一天的收盘价、当天的收盘价、涨跌值、涨跌幅
4. 设置以定点法print数据，只精确到2位小数。查询前10只股票的情况
5. 查询涨幅高于10%的股票
6. 查询前20只股票的当天收盘价与涨跌幅
7. 已知A购买了前20只股票，各股票的数量按顺序为：
    100,200,300,150,500,600,700,550,900,1000,100,100,100,200,300,800,550,150,900,1000
    
    请计算A当天的所购股票的总市值、总收益
    
    (正确结果是：总市值 182955.5 总收益 480.50000000000284）
8. 求购买股票的数量总和、最小数量

    （正确结果是：股票总数量 9200 最小数量 100）
9. 将股票按涨跌幅降序排序，排序结果如下：

~~~
 [[ 29.5   33.99   4.49   0.15]
 [139.82 155.36  15.54   0.11]
 [ 85.5   95.     9.5    0.11]
 ...
 [ 56.72  47.27  -9.45  -0.17]
 [ 50.83  42.36  -8.47  -0.17]
 [ 46.48  38.73  -7.75  -0.17]]
 ~~~

In [2]:
import numpy as np
#读取文件
stock=np.loadtxt(".//stock0.txt", delimiter='\t',encoding='utf-16') 
print(stock)  

[[12.72 12.17]
 [ 4.8   4.36]
 [22.4  22.6 ]
 ...
 [ 6.13  6.12]
 [ 4.68  4.6 ]
 [ 4.95  4.94]]


In [3]:
#跌涨值
udvalue=stock[:,1]-stock[:,0]
print(udvalue)

[-0.55 -0.44  0.2  ... -0.01 -0.08 -0.01]


In [4]:
#跌涨幅
udfrequency=udvalue/stock[:,0]
print(udfrequency)

[-0.04323899 -0.09166667  0.00892857 ... -0.00163132 -0.01709402
 -0.0020202 ]


In [21]:
#合并
udvalue=udvalue.reshape(6000,1)
udfrequency=udfrequency.reshape(6000,1)
alData=np.hstack((stock,udvalue,udfrequency))
# alData=np.concatenate((stock,udvalue,udfrequency),axis=1)
print(alData)

[[ 1.27200000e+01  1.21700000e+01 -5.50000000e-01 -4.32389937e-02]
 [ 4.80000000e+00  4.36000000e+00 -4.40000000e-01 -9.16666667e-02]
 [ 2.24000000e+01  2.26000000e+01  2.00000000e-01  8.92857143e-03]
 ...
 [ 6.13000000e+00  6.12000000e+00 -1.00000000e-02 -1.63132137e-03]
 [ 4.68000000e+00  4.60000000e+00 -8.00000000e-02 -1.70940171e-02]
 [ 4.95000000e+00  4.94000000e+00 -1.00000000e-02 -2.02020202e-03]]


In [25]:
#格式化输出前10个元素
np.set_printoptions(precision=2,floatmode="fixed",suppress=True)
print(alData[:10])

[[12.72 12.17 -0.55 -0.04]
 [ 4.80  4.36 -0.44 -0.09]
 [22.40 22.60  0.20  0.01]
 [38.35 40.40  2.05  0.05]
 [24.88 25.05  0.17  0.01]
 [ 1.79  1.80  0.01  0.01]
 [24.58 24.31 -0.27 -0.01]
 [62.15 62.76  0.61  0.01]
 [ 2.76  2.73 -0.03 -0.01]
 [11.33 11.40  0.07  0.01]]


In [22]:
#取涨幅>10%的元素
print(alData[alData[:,3]>0.1])

[[7.80000000e+00 8.66000000e+00 8.60000000e-01 1.10256410e-01]
 [5.23000000e+00 5.81000000e+00 5.80000000e-01 1.10898662e-01]
 [1.40600000e+01 1.56100000e+01 1.55000000e+00 1.10241821e-01]
 [8.06000000e+00 8.91000000e+00 8.50000000e-01 1.05459057e-01]
 [6.30000000e+00 6.99000000e+00 6.90000000e-01 1.09523810e-01]
 [1.39820000e+02 1.55360000e+02 1.55400000e+01 1.11142898e-01]
 [2.95000000e+01 3.39900000e+01 4.49000000e+00 1.52203390e-01]
 [3.79000000e+00 4.21000000e+00 4.20000000e-01 1.10817942e-01]
 [8.66000000e+00 9.62000000e+00 9.60000000e-01 1.10854503e-01]
 [8.55000000e+01 9.50000000e+01 9.50000000e+00 1.11111111e-01]]


In [ ]:
#取前20天股票的收盘价与涨跌幅
print(alData[:20,[1,3]])

[[ 1.21700000e+01 -4.32389937e-02]
 [ 4.36000000e+00 -9.16666667e-02]
 [ 2.26000000e+01  8.92857143e-03]
 [ 4.04000000e+01  5.34550196e-02]
 [ 2.50500000e+01  6.83279743e-03]
 [ 1.80000000e+00  5.58659218e-03]
 [ 2.43100000e+01 -1.09845403e-02]
 [ 6.27600000e+01  9.81496380e-03]
 [ 2.73000000e+00 -1.08695652e-02]
 [ 1.14000000e+01  6.17828773e-03]
 [ 4.12000000e+00  9.80392157e-03]
 [ 1.78300000e+01 -5.81088220e-02]
 [ 1.04300000e+01 -1.91387560e-03]
 [ 8.23000000e+00 -2.48815166e-02]
 [ 1.74800000e+01 -3.31858407e-02]
 [ 5.31000000e+00 -1.87969925e-03]
 [ 3.28300000e+01  1.23342584e-02]
 [ 1.44600000e+01 -1.83299389e-02]
 [ 3.90200000e+01  4.11734431e-03]
 [ 1.93100000e+01 -5.17598344e-04]]


In [28]:
#计算A当天的所购股票的总市值、总收益
quantities=np.array([100,200,300,150,500,600,700,550,900,1000,100,100,100,200,300,800,550,150,900,1000])
tvalue=np.sum(alData[:20,1]*quantities)
tprofit=np.sum(alData[:20,2]*quantities)
print(f"总市值:{tvalue} 总收益:{tprofit}")

总市值:182955.5 总收益:480.50000000000284


In [29]:
#求购买股票的数量总和、最小数量
print(f"数量总和:{np.sum(quantities)} 最小数量:{np.min(quantities)}")

数量总和:9200 最小数量:100


In [30]:
#按跌涨幅降序排序
sorted_by=np.argsort(-alData[:,3])
sortedData=alData[sorted_by]
print(sortedData)

[[ 29.50  33.99   4.49   0.15]
 [139.82 155.36  15.54   0.11]
 [ 85.50  95.00   9.50   0.11]
 ...
 [ 56.72  47.27  -9.45  -0.17]
 [ 50.83  42.36  -8.47  -0.17]
 [ 46.48  38.73  -7.75  -0.17]]
